Blog.WebApp/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog.WebApp.Models;

namespace Blog.WebApp.Controllers
{ 
    public class CommentsController : Controller
    {
        private readonly ICommentsRepository commentsRepository;
        private BlogContext db = new BlogContext();

        public CommentsController(ICommentsRepository commentsRepository)
        {
            this.commentsRepository = commentsRepository;
        }

        [HttpPost]
        public ActionResult Create(Comment comment)
        {
            commentsRepository.Save(comment);
            return RedirectToAction("Index", "Home");  
        }
    }
}

Blog.WebApp/Controllers/HomeController.cs
using System.Web.Mvc;
using Blog.WebApp.Models;

namespace Blog.WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly IPostsRepository postsRepository;

        public HomeController(IPostsRepository postsRepository)
        {
            this.postsRepository = postsRepository;
        }

        public ActionResult Index()
        {
            var posts = postsRepository.All();
            return View(posts);
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

Blog.WebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Us";
}

<h2>About</h2>
<p>
     Put content here.
</p>

Blog.WebApp/Views/Home/Index.cshtml
@using Blog.WebApp.Models
@model IEnumerable<Blog.WebApp.Models.Post>
           
@{
    ViewBag.Title = "Home Page";
}

<div>
    @foreach (Post post in Model)
    {
        <a href="#@post.Id"></a>
        <h1>@post.Titulo</h1>
        <div>@post.Corpo</div>
        <p>Postado por @post.Autor em @post.Data.ToShortDateString()</p>
        <div class="comment">
            @using (Html.BeginForm("Create", "Comments"))
            {
                <p>Autor: @Html.TextBox("Author")</p>
                <p>Comentário: @Html.TextArea("Body")</p>
                <input type="submit" value="Comentar"/>
            }
        </div>
        
    }
</div>